repos:
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: "mypy"
        language: system
        exclude: ^tests/
        types: [python]
        verbose: true
-   repo: local
    hooks:
    -   id: pytest
        name: run tests
        entry: pytest tests
        language: system
        always_run: true
        pass_filenames: false
